# Generated by Django 4.2.2 on 2024-06-09 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="likecount",
            options={"verbose_name_plural": "点赞数"},
        ),
        migrations.AlterModelOptions(
            name="likerecord",
            options={"verbose_name_plural": "点赞记录"},
        ),
    ]
