# Generated by Django 4.2.2 on 2024-05-31 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read_count", "0002_readdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readdetail",
            old_name="data",
            new_name="date",
        ),
    ]
