# Generated by Django 4.2.2 on 2024-05-31 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("read_count", "0003_rename_data_readdetail_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readdetail",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
