# Generated by Django 4.2.2 on 2024-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read_count", "0004_alter_readdetail_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readdetail",
            name="object_id",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
