# Generated by Django 4.2.2 on 2024-06-01 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read_count", "0007_alter_readdetail_object_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readdetail",
            options={"verbose_name_plural": "日访问量"},
        ),
        migrations.AlterModelOptions(
            name="readnum",
            options={"verbose_name_plural": "总访问量"},
        ),
    ]
