# Generated by Django 4.2.2 on 2024-05-25 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="created",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="last_updated",
            new_name="last_updated_time",
        ),
    ]
