# Generated by Django 4.2.2 on 2024-05-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blog_blog",
                to="blog.blogtype",
            ),
        ),
    ]
