# Generated by Django 4.2.2 on 2024-05-29 22:20

from django.db import migrations
import ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_blog_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
