# Generated by Django 4.2.2 on 2024-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="read",
            field=models.IntegerField(default=0),
        ),
    ]
