# Generated by Django 4.2.2 on 2024-05-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_blog_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="read",
        ),
        migrations.CreateModel(
            name="ReadNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.IntegerField(default=0)),
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="blog.blog"
                    ),
                ),
            ],
        ),
    ]
