# Generated by Django 4.2.2 on 2024-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_remove_blog_read_readnum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readnum",
            old_name="read",
            new_name="read_num",
        ),
    ]
