# Generated by Django 4.2.2 on 2024-06-09 16:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_profile_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
