# Generated by Django 4.2.2 on 2024-06-12 15:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar/%Y%m%d/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
