# Generated by Django 4.2.2 on 2024-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_profile_avatar_alter_profile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar/default.jpg", upload_to="avatar/%Y%m%d/"
            ),
        ),
    ]
