# Generated by Django 4.2.2 on 2024-06-12 15:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="这个家伙很神秘", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                blank=True, default="暂无昵称", max_length=20, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="暂无号码", max_length=20),
        ),
    ]
