# Generated by Django 4.2.2 on 2024-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_profile_bio_alter_profile_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=20, verbose_name="昵称"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="号码"),
        ),
    ]
