# Generated by Django 4.2.2 on 2024-06-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-comment_time",), "verbose_name_plural": "评论"},
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_id",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="comment.comment",
                    ),
                ),
            ],
        ),
    ]
